update

diff --git a/tmux-cmd b/tmux-cmd
--- a/tmux-cmd
+++ b/tmux-cmd
@@ -1,22 +1,82 @@
 #!/bin/bash
+
+# tmux-cmd: compilation of tmux scripts
+
+[ ! "$(command -V "tmux")" ] && exit 1
+[ ! "$(command -V "fzf")" ] && exit 1
+
 TMUX_RUNNING=$(pgrep tmux)
 
+# paths that would be sessionize by default
+PROJECT_DIR=(
+    "$HOME/Programming/repositories"
+    "$HOME/Programming/work_in_progress"
+    "$HOME/Programming/godot"
+)
+
+# prints the error message
 error()
 {
-    printf "%s\n" "$1" 2>/dev/null
+    printf "%s\n" "$1" >&2
+    [ -n "$TMUX_RUNNING" ] && tmux display-message "$1" >&2
     exit 1
 }
 
+# checks if project is a godot project
+is_godot_project()
+{
+    path="$1"
+
+    if [ -f "$path/project.godot" ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+# checks if a program is installed
+is_installed()
+{
+    program="$1"
+
+    if [ "$(command -V "$program")" ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+session_is_attached()
+{
+    session_name="$1"
+
+    if ! tmux has-session -t="$session_name" 2> /dev/null; then
+        error "No session named '$session_name'"
+    fi
+
+    session_status="$(tmux list-sessions -F "#{session_name} #{session_attached}" | \
+        grep -w -v "$1" | cut -d " " -f2)"
+
+    if [ "$session_status" -eq 1 ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 # creates a window
-new_window()
+create_new_window()
 {
     session_name="$1"
     window_name="$2"
     cmd="$3"
+    path="$4"
 
-    tmux new-window -t "$session_name" 
+    [ -z "$path" ] || [ ! -d "$path" ] && path="$HOME"
+
+    tmux new-window -t "$session_name" -c "$path" 
     tmux rename-window -t "$session_name" "$window_name"
-    tmux send-keys -t "$session_name" "$cmd" C-m
+    [ -n "$cmd" ] && tmux send-keys -t "$session_name" "$cmd" C-m
 }
 
 # setups the window layouts
@@ -24,108 +84,129 @@ create_workspace()
 {
     session_name="$1"
     path="$2"
-    sel_window="1"
 
+    main_window="1"
+
+    neovim="nvim"
+    neovim_godot="$neovim --listen ./godothost ."
+    
     tmux rename-window -t "$session_name" "ED"
-    tmux send-keys -t "$session_name" "nvim" C-m
 
-    # new_window "$session_name" "FM" "ranger"
+    if is_godot_project "$path"; then
+        tmux send-keys -t "$session_name" "$neovim_godot" C-m
+        tmux display-message \
+            "Godot project detected... listening to 'godothost' server..."
+    else
+        tmux send-keys -t "$session_name" "$neovim" C-m
+    fi
 
-    tmux new-window -t "$session_name" -c "$path"
-    tmux rename-window -t "$session_name" "TERM"
-
-    tmux select-window -t "$session_name:$sel_window"
+    create_new_window "$session_name" "TERM" "" "$path"
+    tmux select-window -t "$session_name:$main_window"
 }
 
 # starting session
 tmux_start()
 {
     session_name="MAIN"
+    path="$HOME"
+    
+    win_1_title="TASK"
+    win_1_cmd="calcurse"
+
+    win_2_title="FILE"
+    win_2_cmd="ranger"
+
+    win_3_title="MUSIC"
+    win_3_cmd="cmus"
 
     if ! tmux has-session -t="$session_name" 2> /dev/null; then
+        # the first window is path when finished
         sel_window="1"
-
+        
+        # create the session
         tmux new-session -ds "$session_name" -c "$HOME"
+        
+        # create the windows
 
-        tmux rename-window -t "$session_name" "TASK"
-        tmux send-keys -t "$session_name" "calcurse" C-m
+        # window 1
+        if is_installed "$win_1_cmd"; then
+            tmux rename-window -t "$session_name" "$win_1_title"
+            tmux send-keys -t "$session_name" "$win_1_cmd" C-m
+        fi
 
-        new_window "$session_name" "FILE" "ranger"
-        new_window "$session_name" "MUSIC" "cmus"
+        # window 2
+        is_installed "$win_2_cmd" && \
+            create_new_window "$session_name" "$win_2_title" "$win_2_cmd"
 
+        # window 3
+        is_installed "$win_3_cmd" && \
+            create_new_window "$session_name" "$win_3_title" "$win_3_cmd"
+        
+        # go back to the first window
         tmux select-window -t "$session_name:$sel_window"
-    fi
+        tmux attach-session -t "$session_name"
 
-    tmux switch-client -t "$selected_name" \
-        || tmux attach-session -t "$selected_name"
+    else
+        tmux switch-client -t "$session_name"
+    fi
 }
 
-# switch to a selected session and kill the previous session
-switch_and_kill()
+# go to a selected session than kill the previous focused session
+switch_n_kill()
 {
     [ -z "$TMUX" ] && [ -z "$TMUX_RUNNING" ] && error "Tmux is not running"
 
     last_active_session="$(tmux list-sessions -F "#{session_activity} #{session_name}" | \
         sort -n | tail -n 1 | cut -d " " -f2-)"
 
-    session_target="$(tmux list-sessions | \
+    switch_target="$(tmux list-sessions | \
         grep -w -v "$last_active_session" | fzf | cut -d ":" -f1)"
 
-    target_is_attached="$(tmux list-sessions -F "#{session_name}:#{session_attached}" | \
-        grep -w -v "$session_target" | cut -d ":" -f2)"
+    session_is_attached "$switch_target" && tmux detach -s "$switch_target"
 
-    [ "$target_is_attached" -eq 1 ] && tmux detach -s "$session_target"
-
-    tmux switch-client -t "$session_target"
+    tmux switch-client -t "$switch_target"
     tmux kill-session -t "$last_active_session"
 }
 
 # creates sessions
 sessionize()
 {
-    PROJECT_DIR=(
-        "$HOME/Programming/repositories"
-        "$HOME/Programming/work_in_progress"
-    )
-
     case "$1" in
         # sessionize a specified directory
 	    -target) 
             [ ! -d "$2" ] && error "Target '$2' is not a directory"
-            selected="$2"
+            path="$2"
         ;;
 
         # sessionize the current working directory
-        -cwd) selected="$(find -L "$(pwd)" -mindepth 1 -maxdepth 2 -type d | fzf)" ;;
+        -cwd) path="$(find -L "$(pwd)" -mindepth 1 -maxdepth 2 -type d | fzf)" ;;
 
         # sessionize a directory from the PROJECT_DIR
-        -project) selected="$(find -L "${PROJECT_DIR[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)";;
+        *) path="$(find -L "${PROJECT_DIR[@]}" -mindepth 1 -maxdepth 1 -type d | fzf)";;
     esac
 
-    [ -z "$selected" ] || [ ! -d "$selected" ] &&  error "invalid selection '$selected'"
+    [ -z "$path" ] || [ ! -d "$path" ] &&  error "invalid selection '$path'"
 
-    selected_name=$(basename "$selected" | tr . _)
+    session_name=$(basename "$path" | tr . _)
 
     if [ -z "$TMUX" ] && [ -z "$TMUX_RUNNING" ]; then
-        tmux new-session -s "$selected_name" -c "$selected"
+        tmux new-session -s "$session_name" -c "$path"
         exit 0
     fi
 
-    if ! tmux has-session -t="$selected_name" 2> /dev/null; then
-        tmux new-session -d -s "$selected_name" -c "$selected"
-        create_workspace "$selected_name" "$selected"
+    if ! tmux has-session -t="$session_name" 2> /dev/null; then
+        tmux new-session -d -s "$session_name" -c "$path"
+        create_workspace "$session_name" "$path"
     fi
 
-    tmux switch-client -t "$selected_name" \
-        || tmux attach-session -t "$selected_name"
+    tmux switch-client -t "$session_name" \
+        || tmux attach-session -t "$session_name"
 }
 
 case "$1" in
     -start) tmux_start ;;
-
-    -switch_n_kill) switch_and_kill ;;
-
+    -switch_n_kill) switch_n_kill;;
 	-sessionize-target) sessionize -target "$2" ;;
 	-sessionize-cwd) sessionize -cwd ;;
-    -sessionize-project) sessionize -project ;;
+    -sessionize-project) sessionize;;
 esac
